export const keyboard_colors = new Map([
    ["A", "#d3d6da"],
    ["B", "#d3d6da"],
    ["C", "#d3d6da"],
    ["D", "#d3d6da"],
    ["E", "#d3d6da"],
    ["F", "#d3d6da"],
    ["G", "#d3d6da"],
    ["H", "#d3d6da"],
    ["I", "#d3d6da"],
    ["J", "#d3d6da"],
    ["K", "#d3d6da"],
    ["L", "#d3d6da"],
    ["M", "#d3d6da"],
    ["N", "#d3d6da"],
    ["O", "#d3d6da"],
    ["P", "#d3d6da"],
    ["Q", "#d3d6da"],
    ["R", "#d3d6da"],
    ["S", "#d3d6da"],
    ["T", "#d3d6da"],
    ["U", "#d3d6da"],
    ["V", "#d3d6da"],
    ["W", "#d3d6da"],
    ["X", "#d3d6da"],
    ["Y", "#d3d6da"],
    ["Z", "#d3d6da"],
  ]);
